### PR TITLE
BREAKING: Don't check in generated parser.c file

### PR DESCRIPTION
**Pull request by pfoerster**

### CODE REVIEW

**Comment by clason** [comment]
Note: this is a breaking change for downstream consumers, better mark it as such.

And could you please keep `grammar.json` committed? This is much smaller, has meaningful diffs, and allows faster generation than `grammar.js` (`tree-sitter generate src/grammar.json`).

**Comment by clason** [comment]
Also, consider https://github.com/tree-sitter/workflows

**Comment by clason** [comment]
(Disregard my suggestion about `grammar.json`; it doesn't seem to make a serious difference for this parser -- it did for other, smaller ones. So there's no big benefit for this parser; it's mostly useful for languages that import other languages, where generating from `grammar.js` -- but not from `grammar.json` -- requires `npm`. I was hoping to be able to unify this in nvim-treesitter to always use `tree-sitter generate src/grammar.json`, but that is not necessarily a compelling argument for you.)

**Comment by pfoerster** [comment]
@clason Well, it looks like checking in `parser.c` still seems to be the recommended way so I guess I'll keep the existing structure for now to avoid the breaking changes downstream.

> Also, consider https://github.com/tree-sitter/workflows; see https://github.com/tree-sitter-grammars/template

Thanks, these look very good!

**Comment by clason** [comment]
> @clason Well, it looks like checking in parser.c still seems to be the recommended way so I guess I'll keep the existing structure for now to avoid the breaking changes downstream.

Well, officially the recommended way is
1. keep `parser.c` out of the repo
2. make frequent semver releases _with_ `parser.c`

What's not yet done is adding support to `tree-sitter` CLI to make 2. easier.

**Comment by lnay** [comment]
> 2\. make frequent semver releases _with_ `parser.c`.

Has there been any such releases since v0.0.4? I'm working on a Zed extension and it seems that Zed only likes repos for grammars that include `parser.c`. For now I'm pointing to the parent of tag v0.0.4, I couldn't find any other branches here that include this file, is that indeed the case?

**Comment by clason** [comment]
No, this is blocked by upstream (tree-sitter) development that adds release and publish workflows. If you want to use this parser, you need to generate it first (`tree-sitter generate --no-bindings`) .

**Comment by lnay** [comment]
Brunsfeld? Is the idea that a workflow would branch on each tag adding an extra commit including the generated files?

**Comment by clason** [comment]
Yes, and ideally the wasm. The issue is that you need generated files on top of the full repo contents (and compiling to wasm is not trivial). Ideally, a workflow uses tree-sitter CLI to generate and package them, then upload to GitHub.

**Pull request merged**
